#!/bin/sh -eu

cd "$(dirname "$0")/.."

nix run \
    --ignore-environment \
    --file ./support \
    nix-project-exe \
    --command \
    nix-project \
    --upgrade \
    --source-dir '.' \
    --nix "$(command -v nix)" \
    "$@"
