#!/bin/sh -eu

cd "$(dirname "$0")/.."

# NOTE: because of --ignore-environment, you control _exactly_ what executables
# are on PATH when generating documentation with Org2gfm.  Below, only coreutils
# is on PATH.  You can change the line below to include other binaries from
# Nixpkgs or any package from any flake you like.
nix shell \
    --ignore-environment \
    --keep HOME \
    --keep LANG \
    --keep LOCALE_ARCHIVE \
    .#infra.np.nixpkgs.stable.ansifilter \
    .#infra.np.nixpkgs.stable.coreutils \
    .#infra.np.nixpkgs.stable.git \
    .#infra.np.nixpkgs.stable.gnugrep \
    .#infra.np.nixpkgs.stable.jq \
    .#infra.np.nixpkgs.stable.nixfmt \
    .#infra.np.nixpkgs.stable.org2gfm \
    .#infra.np.nixpkgs.stable.tree \
    --command \
    org2gfm \
    --path-bin \
    --exclude internal \
    --nix "$(command -v nix)" \
    --evaluate \
    "$@"
