#!/bin/sh -eu

cd "$(dirname "$0")/.."

nix shell \
    --ignore-environment \
    --keep HOME \
    --keep LANG \
    --keep LOCALE_ARCHIVE \
    .#infra.np.nixpkgs.stable.ansifilter \
    .#infra.np.nixpkgs.stable.coreutils \
    .#infra.np.nixpkgs.stable.git \
    .#infra.np.nixpkgs.stable.gnugrep \
    .#infra.np.nixpkgs.stable.jq \
    .#infra.np.nixpkgs.stable.nixfmt \
    .#infra.np.nixpkgs.stable.org2gfm \
    .#infra.np.nixpkgs.stable.tree \
    --command \
    org2gfm \
    --path-bin \
    --exclude internal \
    --nix "$(command -v nix)" \
    --evaluate \
    "$@"
