#!/bin/sh -eu


cd "$(dirname "$0")/.."

for category in common darwin linux
do mkdir --parent \
    "infrastructure/haskell-nix/materialized-$category"
done

nix-build --no-out-link -A updateMaterialized | \
    while read -r script
    do
        echo
        echo "###"
        echo "### Update Materialization: $script"
        echo "###"
        echo
        "$script"
    done
