#!/bin/sh -eu


cd "$(dirname "$0")/.."
CACHE=https://cache.nixos.org/


main()
(
    BUILD_PATH="$(build_path)"
    find "$BUILD_PATH" -maxdepth 1 -mindepth 1 | while read -r link
    do check "$(readlink -f "$link")"
    done
)

build_path()
{
    nix build --no-link --print-out-paths .#ci.all
}

check()
{
    if passes_check "$(store_hash "$1")"
    then echo "CACHED: $1"
    else echo "UNCACHED: $1"
    fi
}

passes_check()
{
    curl --silent --head --fail "$CACHE$1.narinfo" \
    >/dev/null
}

store_hash()
(
    INPUT_SUFFIX="${1#/nix/store/}"
    echo "${INPUT_SUFFIX%%-*}"
)


main "$@"
