#!/usr/bin/env sh

# DESIGN: these moved somewhere else.  Probably never going to use the bar, but
# don't feel like deleting these because hunting down Unicode is tedious.
#
# bar settings
# yabai -m config status_bar                   on
# yabai -m config status_bar_text_font         "Helvetica Neue:Bold:14.0"
# yabai -m config status_bar_icon_font         "Font Awesome 5 Free:Solid:14.0"
# yabai -m config status_bar_background_color  0xff202020
# yabai -m config status_bar_foreground_color  0xffa8a8a8
# yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
# yabai -m config status_bar_power_icon_strip   
# yabai -m config status_bar_space_icon        
# yabai -m config status_bar_clock_icon        


# initialization
# DESIGN: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                on
yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xffb58900
yabai -m config normal_window_border_color   0xff586e75
yabai -m config insert_feedback_color        0xffd75f00
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

# custom rules
yabai -m rule --add app=Emacs title='^.+$' manage=on

echo "yabai configuration loaded.."
