#!/bin/sh -eu

cd "$(dirname "$0")"

nix run \
    --ignore-environment \
    --keep DBUS_SESSION_BUS_ADDRESS \
    --keep HOME \
    --keep TERM \
    --keep TERMINFO \
    --keep USER \
    --file . \
    infra.np.nixpkgs-stable.shajra-home-manager \
    --command \
    shajra-home-manager \
    --nix "$(command -v nix-build)" \
    "$@"
