#+TITLE: Personal Nix Expression of Packages
#+SETUPFILE: ./support/setup.org

[[https://github.com/shajra/shajra-nix-packages/actions][https://github.com/shajra/shajra-nix-packages/workflows/CI/badge.svg]]

* About this project

  This project has a [[nix][Nix]] expression for the Nix packages I install on my
  personal laptop. Later on it may have packages for more machines. For now,
  the expression evaluates to an attribute set of package derivations.

  The likelihood that anyone else will want the exact packages I use is slim.
  Still, you can look at this project to see how I manage my expressions.

  If I build something you like, you can import my expression into your own and
  select the packages of your choosing, benefiting from the cached build in my
  personal [[cachix][Cachix]] instance.

  See [[file:doc/nix.org][the provided documentation on Nix]] for more on what Nix is, why we're
  motivated to use it, and how to get set up with it for this project.

* Using the project

  #+INCLUDE: "doc/nix.org::*Nix package manager setup"

  #+INCLUDE: "doc/nix.org::*Cache setup"

** Installing the programs

   You can layer my programs on top of previously installed programs with the
   following call:

   #+BEGIN_SRC shell :eval no
     nix-env --install --file .
   #+END_SRC

   =nix-env= maintains a symlink tree of all installed packages at
   =~/.nix-profile=, so set your =PATH= variable accordingly if it's not
   already set from your Nix installation:

   #+BEGIN_SRC shell :eval no
     export PATH="$HOME/.nix-profile/bin:$PATH"
   #+END_SRC

* Release

  The "master" branch of the repository on GitHub has the latest released
  version of this code. There is currently no commitment to either forward or
  backward compatibility.

  "user/shajra" branches are personal branches that may be force-pushed to. The
  "master" branch should not experience force-pushes and is recommended for
  general use.

* License

  All files in this "shajra-nix-packages" project are licensed under the terms
  of GPLv3 or (at your option) any later version.

  Please see the [[./COPYING.md][./COPYING.md]] file for more details.

* Contribution

  Feel free to file issues and submit pull requests with GitHub.

  There is only one author to date, so the following copyright covers all files
  in this project:

  Copyright © 2020 Sukant Hajra
